@startuml
'https://plantuml.com/class-diagram

hide empty member

class Game {
    -Board board
    -Player[] players
}

package Player {
    class Player {
       -Inventory inventory
    }

    class Inventory {
        -int[] resourceCount
        -int[] productionCount
    }

    Player -> Inventory
}

package Board {
    class Board {
     -List<Cell> cells
     +placeTile(Player player, Tile tile, Cell cell)
    }

    class Cell {
     -Tile tile
     -Player player
    }

    interface Tile {

    }

    Board -> Tile
    Board -> Cell
    Cell -> Tile
}

@enduml